"""Stop word lists for 6 languages — used for water % calculation."""

STOP_WORDS = {
    "uk": {
        "і", "в", "у", "на", "з", "за", "до", "від", "по", "про", "при", "для", "як",
        "що", "це", "та", "але", "а", "або", "чи", "не", "ні", "так", "ще", "вже",
        "він", "вона", "воно", "вони", "я", "ми", "ви", "ти", "мій", "твій", "наш",
        "ваш", "їх", "його", "її", "свій", "цей", "той", "такий", "який", "кожний",
        "весь", "сам", "інший", "один", "два", "три", "був", "була", "було", "були",
        "є", "буде", "будуть", "бути", "може", "можна", "треба", "потрібно", "слід",
        "також", "тому", "тут", "там", "тоді", "коли", "де", "куди", "звідки",
        "якщо", "хоча", "проте", "однак", "через", "між", "під", "над", "перед",
        "після", "без", "ж", "би", "б", "же", "ось", "от", "лише", "тільки",
        "більш", "менш", "дуже", "все", "усе", "усі", "всі", "багато", "мало",
        "якого", "якої", "яких", "яким", "якому", "цього", "цієї", "цих", "тих",
    },
    "en": {
        "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
        "have", "has", "had", "do", "does", "did", "will", "would", "could",
        "should", "may", "might", "must", "shall", "can", "need", "dare",
        "to", "of", "in", "for", "on", "with", "at", "by", "from", "as",
        "into", "through", "during", "before", "after", "above", "below",
        "between", "out", "off", "over", "under", "again", "further", "then",
        "once", "here", "there", "when", "where", "why", "how", "all", "both",
        "each", "few", "more", "most", "other", "some", "such", "no", "nor",
        "not", "only", "own", "same", "so", "than", "too", "very", "just",
        "and", "but", "or", "if", "while", "because", "until", "although",
        "it", "its", "this", "that", "these", "those", "i", "me", "my",
        "we", "our", "you", "your", "he", "him", "his", "she", "her",
        "they", "them", "their", "what", "which", "who", "whom", "about",
        "also", "well", "back", "even", "still", "way", "take", "since",
    },
    "ru": {
        "и", "в", "на", "с", "за", "к", "по", "от", "из", "у", "о", "для", "как",
        "что", "это", "но", "а", "или", "не", "да", "ещё", "уже", "он", "она",
        "оно", "они", "я", "мы", "вы", "ты", "мой", "твой", "наш", "ваш", "их",
        "его", "её", "свой", "этот", "тот", "такой", "какой", "каждый", "весь",
        "сам", "другой", "один", "два", "три", "был", "была", "было", "были",
        "есть", "будет", "будут", "быть", "может", "можно", "надо", "нужно",
        "также", "потому", "тут", "там", "тогда", "когда", "где", "куда", "откуда",
        "если", "хотя", "однако", "через", "между", "под", "над", "перед",
        "после", "без", "же", "бы", "ли", "вот", "вон", "лишь", "только",
        "более", "менее", "очень", "все", "всё", "много", "мало", "при", "про",
        "чтобы", "чем", "так", "то", "до", "ни", "ну", "уж", "которой",
        "которого", "которых", "которым", "которому", "который", "которая",
        "которое", "которые", "того", "этих", "тех", "этой", "эти",
    },
    "pl": {
        "i", "w", "na", "z", "za", "do", "od", "po", "o", "dla", "jak",
        "co", "to", "ale", "a", "lub", "nie", "tak", "jeszcze", "już",
        "on", "ona", "ono", "oni", "one", "ja", "my", "wy", "ty", "mój",
        "twój", "nasz", "wasz", "ich", "jego", "jej", "swój", "ten", "ta",
        "te", "taki", "jaki", "każdy", "cały", "sam", "inny", "jeden", "dwa",
        "trzy", "był", "była", "było", "byli", "jest", "będzie", "będą", "być",
        "może", "można", "trzeba", "potrzeba", "również", "także", "dlatego",
        "tu", "tam", "wtedy", "kiedy", "gdzie", "dokąd", "skąd", "jeśli",
        "chociaż", "jednak", "przez", "między", "pod", "nad", "przed",
        "po", "bez", "że", "by", "się", "czy", "oto", "tylko", "jedynie",
        "bardzo", "wszystko", "wiele", "mało", "przy", "które", "który",
        "która", "którego", "której", "których", "którym", "tych", "tego",
    },
    "es": {
        "y", "en", "de", "a", "el", "la", "los", "las", "un", "una", "unos",
        "unas", "es", "son", "fue", "ser", "estar", "ha", "han", "del", "al",
        "por", "para", "con", "sin", "sobre", "entre", "desde", "hasta",
        "como", "que", "pero", "o", "ni", "no", "sí", "ya", "aún", "más",
        "menos", "muy", "también", "este", "esta", "estos", "estas", "ese",
        "esa", "esos", "esas", "aquel", "aquella", "yo", "tú", "él", "ella",
        "nosotros", "ellos", "ellas", "me", "te", "se", "le", "lo", "nos",
        "les", "su", "sus", "mi", "tu", "nuestro", "nuestra", "todo", "toda",
        "todos", "todas", "otro", "otra", "otros", "cada", "mismo", "misma",
        "donde", "cuando", "quien", "cual", "cuyo", "si", "porque", "aunque",
        "sino", "tanto", "tan", "así", "aquí", "ahí", "allí", "hay", "puede",
        "poder", "hacer", "tiene", "tener", "debe", "deber", "solo", "cual",
    },
    "tr": {
        "ve", "bir", "bu", "da", "de", "ile", "için", "den", "dan", "mi",
        "mı", "mu", "mü", "ne", "o", "ya", "en", "çok", "daha", "gibi",
        "olan", "olarak", "ancak", "ama", "fakat", "veya", "hem", "ya da",
        "ise", "ki", "kadar", "sonra", "önce", "arasında", "üzerinde",
        "altında", "içinde", "dışında", "karşı", "göre", "doğru", "beri",
        "ben", "sen", "biz", "siz", "onlar", "benim", "senin", "onun",
        "bizim", "sizin", "onların", "şu", "her", "bazı", "tüm", "bütün",
        "başka", "diğer", "aynı", "kendi", "var", "yok", "olan", "oldu",
        "olur", "olabilir", "olan", "değil", "sadece", "bile", "hiç",
        "çünkü", "eğer", "nasıl", "neden", "nerede", "zaman", "kim",
        "hangi", "böyle", "öyle", "şöyle", "eder", "yapar", "olup",
    },
}
