[supervisord]
nodaemon=true
logfile=/var/log/py-services/py-services-supervisord.log
pidfile=/var/run/supervisord.pid

[program:py-services-nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/py-services/py-services-nginx.log
stderr_logfile=/var/log/py-services/py-services-nginx-error.log

[program:py-services-translation-checker]
command=python -u -m services.translation-checker.server
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/py-services/py-services-translation-checker.log
stderr_logfile=/var/log/py-services/py-services-translation-checker-error.log
environment=PYTHONPATH="/app"

[program:py-services-tts-google-chirp3]
command=python -u -m services.tts-google-chirp3.server
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/py-services/py-services-tts-google-chirp3.log
stderr_logfile=/var/log/py-services/py-services-tts-google-chirp3-error.log
environment=PYTHONPATH="/app"

[program:py-services-lira-assistants-api]
command=python -u -m services.lira-assistants-api.server
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/py-services/py-services-lira-assistants-api.log
stderr_logfile=/var/log/py-services/py-services-lira-assistants-api-error.log
environment=PYTHONPATH="/app"

[program:py-services-quality-check]
command=python -u -m services.quality-check.server
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/py-services/py-services-quality-check.log
stderr_logfile=/var/log/py-services/py-services-quality-check-error.log
environment=PYTHONPATH="/app"

[program:py-services-competitor-monitor]
command=python -u -m services.competitor-monitor.server
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/py-services/py-services-competitor-monitor.log
stderr_logfile=/var/log/py-services/py-services-competitor-monitor-error.log
environment=PYTHONPATH="/app"

# Будущие сервисы:
# [program:py-services-original-checker]
# command=python -u -m services.original-checker.server
# directory=/app
# autostart=true
# autorestart=true
# stdout_logfile=/var/log/py-services/py-services-original-checker.log
# stderr_logfile=/var/log/py-services/py-services-original-checker-error.log
# environment=PYTHONPATH="/app"
